# Generated by Django 4.0.3 on 2022-03-20 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0006_delete_deleterequest_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_librarian',
        ),
    ]
