# Generated by Django 4.0.3 on 2022-03-20 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0007_remove_user_is_librarian'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_librarian',
            field=models.BooleanField(default=False),
        ),
    ]
