# Generated by Django 4.0.3 on 2022-03-25 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0010_user_is_email_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_email_verified',
        ),
    ]
